from pathlib import Path
root = Path('data')
files = {
    'greetings_training.txt': [
        'hey', 'hi', 'hello', 'yo', 'what up', 'sup', 'good morning', 'good afternoon', 'good evening', 'hey there',
        'hiya', 'hiya there', 'hiya bro', 'hey fam', 'howdy', 'hey babe', 'hey dude', 'hey man', 'hey girl', 'hey buddy',
        'how are you', 'are you there', 'u there', 'you there', 'whats up', 'what are you doing', 'still there', 'you awake', 'are you awake', 'hey hey',
        'long time no see', 'i am back', 'i\'m back', 'back again', 'just got back', 'i returned', 'i am online again', 'hiya again', 'i\'m here again', 'back now',
        'hello again', 'hey again', 'see you later', 'bye', 'later', 'catch you later', 'talk soon', 'peace', 'bye bye', 'take care',
        'good night', 'night', 'see ya', 'adios', 'ciao', 'salut', 'hola', 'bonjour', 'ola', 'hiya mate',
        'how is it going', 'how are things', 'how goes it', 'how have you been', 'whats good', 'all good', 'you good', 'how you doing', 'how you been', 'what\'s new',
        'good day', 'good to see you', 'nice to see you', 'hiya pal', 'hey bro', 'hey sis', 'hey fam', 'hey team', 'hey love', 'hey friend',
        'wassup', 'wazzupp', 'whats poppin', 'whassup', 'hey boss', 'hey chief', 'hey mate', 'hey broseph', 'hey cousin', 'hey champ',
        'abuja greeting', 'lagos greeting', 'naija greeting', 'how far', 'how far na', 'how you dey', 'how you dey now', 'how body', 'how your body', 'una dey',
        'good morning o', 'good afternoon o', 'good evening o', 'good night o', 'greetings', 'hiya boss', 'hiya friend', 'hiya buddy', 'hi, friend', 'hi bro',
        'morning', 'afternoon', 'evening', 'nighty', 'bye for now', 'see you soon', 'later gator', 'catch ya', 'peace out', 'take it easy',
        'what are you up to', 'are you around', 'still online', 'still up', 'you still there', 'you still awake', 'you there now', 'u still there', 'hey you', 'listen',
        'hello?', 'hi?', 'so are you there', 'hey are you there', 'hello are you there', 'hey are you awake', 'are you free', 'are you free now', 'free now',
        'im back', 'i am back now', 'back here', 'back online', 'back love', 'back yo', 'back peeps', 'i returned now', 'i\'m back now', 'i\'m back again',
        'hey fam how far', 'hey bro how far', 'hey cousin how far', 'hey sis how far', 'hey people', 'hey all', 'hey team', 'hey crew', 'hey gang', 'hey guys',
        'hello mate', 'hello boss', 'hello team', 'hello fam', 'hello bro', 'hey pal', 'hey bro pal', 'hey friend good to see you', 'nice seeing you', 'good to catch you',
        'see you later alligator', 'bye now', 'bye bye now', 'talk later', 'chat later', 'see you soon', 'keep in touch', 'stay safe', 'stay cool', 'ini',
        'hola amigo', 'bonjour mon ami', 'salut', 'ciao ciao', 'ola amigo', 'konnichiwa', 'namaste', 'assalamualaikum', 'salaam', 'shalom',
        'hiya howdy', 'sup bro', 'sup fam', 'sup mate', 'whats good bro', 'whats good fam', 'hello there mate', 'hey whatsup', 'hey you good', 'yoo',
        'hiya there friend', 'hey there friend', 'hi friend', 'hi buds', 'hi fam', 'hello fam', 'hello bro', 'hello sis', 'hey there sis', 'hey there bro',
        'what is up', 'what is poppin', 'what is good', 'how it dey', 'how body now', 'how you dey', 'how your side', 'how your side dey', 'you dey there', 'you dey now',
        'see ya later', 'bye now', 'bye for now', 'i am leaving', 'i gotta go', 'i gotta run', 'gotta jet', 'catch you later', 'later my friend', 'later bro',
        'hey kitty', 'hiya buddy', 'hiya homie', 'hiya bro', 'hey good morning', 'happy morning', 'good morning friend', 'good afternoon friend', 'good evening friend', 'night friend',
        'yo yo', 'yo yo yo', 'hey hey hey', 'hello hello', 'hi hi', 'heyhey', 'whats good', 'whats new', 'what\'s happening', 'what\'s happening bro',
        'long time no chat', 'long time no see', 'been a while', 'been too long', 'finally back', 'finally here', 'i\'m back on', 'back after a break', 'ya back', 'back again now',
        'hi bro, how are you', 'hey fam, wassup', 'hey love, you there', 'yoo fam', 'yo fam', 'yo bro', 'yo sis', 'hiya crew', 'hiya squad', 'hiya people', 'hiya everyone',
        'hey stranger', 'hey bestie', 'hey pal', 'hey partner', 'hey ace', 'hey star', 'hello star', 'hello mate', 'hello champ', 'hello there buddy',
        'are you there bro', 'are you there fam', 'are you there friend', 'are you there now', 'are you there yet', 'anyone there', 'anybody there', 'hello, anyone there', 'is someone there', 'hey is anyone there',
        'bye bye', 'see you', 'later alligator', 'bye for now', 'have a good one', 'take care now', 'take care bro', 'take care fam', 'peace out bro', 'peace out fam',
    ],
    'everyday_conversation_training.txt': [
        'how are you feeling', 'are you okay', 'what did you eat', 'did you sleep well', 'how was work', 'how was school', 'how is your day', 'how is your mood', 'what is for dinner', 'did you eat yet',
        'is it raining', 'how is the weather', 'is it sunny', 'is it cold', 'is it hot', 'did you sleep enough', 'are you tired', 'are you busy', 'what are you doing later', 'any plans today',
        'how was your day', 'did you have a good day', 'what did you do today', 'how did your meeting go', 'how was class', 'how is your family', 'are you hungry', 'what are you cooking', 'want some coffee', 'need a break',
        'are you okay today', 'how do you feel', 'you look tired', 'you look happy', 'you seem quiet', 'you seem busy', 'did you rest', 'did you shower', 'did you eat breakfast', 'did you skip lunch',
        'how is your boss', 'how is your project', 'how is school going', 'how is your job', 'what is your mood', 'are you stressed', 'are you relaxed', 'are you chilled', 'how is your week', 'how is your weekend',
        'what are your plans', 'what do you want to eat', 'what food do you like', 'what is your favorite food', 'do you like pizza', 'do you like noodles', 'do you like burgers', 'do you want snacks', 'are you craving anything', 'what sounds good',
        'did you watch tv', 'did you watch a show', 'did you finish homework', 'did you finish work', 'did you clean your room', 'did you take a walk', 'did you exercise', 'did you drink water', 'did you stretch', 'did you relax',
        'how was the weather today', 'is it raining there', 'is it windy', 'is it cloudy', 'is it snowing', 'is it humid', 'is it breezy', 'is it nice out', 'how hot is it', 'how cold is it',
        'what is on your mind', 'what are you thinking about', 'are you missing someone', 'are you happy', 'are you sad', 'are you excited', 'are you bored', 'are you nervous', 'are you sleepy', 'are you awake',
        'did you have a good meal', 'did you have breakfast', 'did you have lunch', 'did you have dinner', 'did you snack', 'did you cook', 'did you order food', 'did you eat out', 'did you feel full', 'did you eat enough',
        'how is your energy', 'how is your focus', 'how is your appetite', 'how is your creativity', 'how is your patience', 'how is your motivation', 'how is your mood today', 'how is your stress level', 'how is your sleep', 'how is your rest',
        'what did you learn today', 'what was the highlight', 'what was the low point', 'what made you smile', 'what made you tired', 'what made you laugh', 'what made you think', 'what made you feel good', 'what made you feel weird', 'what made you happy',
        'do you want to chat', 'do you want to talk', 'do you want to share', 'do you want to vent', 'do you want advice', 'do you want to joke', 'do you want to relax', 'do you want to rest', 'do you want to eat', 'do you want coffee',
        'how is your family doing', 'how are your kids', 'how is your partner', 'how is your roommate', 'how is your cat', 'how is your dog', 'how is your pet', 'how is your neighbor', 'how is your team', 'how is your class',
        'did you finish your task', 'did you finish your assignment', 'did you finish your study', 'did you finish your shift', 'did you finish your meeting', 'did you finish your lecture', 'did you finish your errands', 'did you finish your chores', 'did you finish your reading', 'did you finish your writing',
        'how was your breakfast', 'how was your lunch', 'how was your dinner', 'how was your snack', 'how was your coffee', 'how was your tea', 'how was your dessert', 'how was your meal', 'how was your smoothie', 'how was your sandwich',
        'did you get enough sleep', 'did you wake up early', 'did you sleep late', 'did you take a nap', 'did you dream', 'did you have a busy day', 'did you have a calm day', 'did you have a fun day', 'did you have a rough day', 'did you have a great day',
        'how do you feel about today', 'how do you feel about work', 'how do you feel about school', 'how do you feel about the weather', 'how do you feel about food', 'how do you feel about your plans', 'how do you feel about tonight', 'how do you feel about this week', 'how do you feel about tomorrow', 'how do you feel about the weekend',
        'what are you eating now', 'what are you drinking now', 'what are you wearing now', 'what are you doing now', 'what are you planning now', 'what are you thinking now', 'what are you feeling now', 'what are you waiting for', 'what are you excited about', 'what are you worried about',
        'did you have a good weekend', 'did you have a good morning', 'did you have a good afternoon', 'did you have a good evening', 'did you have a good night', 'did you have a quiet day', 'did you have a busy morning', 'did you have a slow afternoon', 'did you have a fun evening', 'did you have a restful night',
        'how is your routine', 'how is your schedule', 'how is your break', 'how is your lunch break', 'how is your commute', 'how is your exercise', 'how is your reading', 'how is your study', 'how is your baking', 'how is your cooking',
        'are you still working', 'are you still studying', 'are you still at school', 'are you still on break', 'are you still at home', 'are you still outside', 'are you still sleepy', 'are you still busy', 'are you still awake', 'are you still free',
    ],
    'knowledge_and_problem_solving_training.txt': [
        'what is ai', 'what is machine learning', 'what is neural network', 'what is deep learning', 'what is cloud computing', 'what is blockchain', 'what is a database', 'what is an algorithm', 'what is a model', 'what is a byte',
        'why is ai useful', 'why is machine learning popular', 'why do we use algorithms', 'why does my code crash', 'why is the sky blue', 'why do plants need water', 'why do we sleep', 'why is music soothing', 'why does rain happen', 'why do we learn math',
        'how do i fix a bug', 'how do i learn python', 'how do i make a website', 'how do i train a model', 'how do i save my work', 'how do i play guitar', 'how do i write a song', 'how do i design a logo', 'how do i cook pasta', 'how do i clean my desk',
        'what is generative ai', 'what is natural language processing', 'what is reinforcement learning', 'what is data science', 'what is user experience', 'what is a startup', 'what is product design', 'what is computer vision', 'what is quantum computing', 'what is music theory',
        'why should i learn coding', 'why is data important', 'why is design important', 'why is science helpful', 'why is documentation useful', 'why is sharing knowledge good', 'why is collaboration useful', 'why is practice needed', 'why is curiosity good', 'why is sleep important',
        'how can i build an app', 'how can i improve my writing', 'how can i organize my notes', 'how can i stay motivated', 'how can i learn faster', 'how can i solve this problem', 'how can i debug this', 'how can i make it better', 'how can i find answers', 'how can i get help',
        'what is the difference between ai and ml', 'what is the difference between ui and ux', 'what is the difference between data and information', 'what is the difference between frontend and backend', 'what is the difference between app and website', 'what is the difference between code and script', 'what is the difference between design and art', 'what is the difference between science and engineering', 'what is the difference between tech and tools', 'what is the difference between hardware and software',
        'why do we use keyboards', 'why do we use screens', 'why do we use headphones', 'why do we use apps', 'why do we use social media', 'why do we use search engines', 'why do we use emails', 'why do we use passwords', 'why do we use usernames', 'why do we use updates',
        'how does a phone work', 'how does the internet work', 'how does wifi work', 'how does bluetooth work', 'how does a battery work', 'how does a camera work', 'how does streaming work', 'how does a microphone work', 'how does a speaker work', 'how does a printer work',
        'what is a server', 'what is a browser', 'what is a framework', 'what is a library', 'what is a protocol', 'what is an api', 'what is a sensor', 'what is a chip', 'what is a circuit', 'what is a plugin',
        'why does sound travel', 'why does light bend', 'why does metal rust', 'why does ice melt', 'why does gravity pull', 'why does heat move', 'why does time feel fast', 'why does music make you feel', 'why does art matter', 'why does math help',
        'how do i choose a color', 'how do i balance a layout', 'how do i pick a font', 'how do i name my project', 'how do i set up a workspace', 'how do i charge my device', 'how do i protect my privacy', 'how do i save a file', 'how do i share a link', 'how do i join a call',
        'what is a chord', 'what is a beat', 'what is a melody', 'what is a rhythm', 'what is harmony', 'what is tempo', 'what is a mix', 'what is a genre', 'what is a producer', 'what is a songwriter',
        'why is practice key', 'why is feedback useful', 'why is version control helpful', 'why is backup important', 'why is testing needed', 'why is patience important', 'why is an idea powerful', 'why is empathy important', 'why is learning continuous', 'why is asking questions good',
        'how can i study effectively', 'how can i manage time', 'how can i avoid distraction', 'how can i stay focused', 'how can i prepare for tests', 'how can i learn by doing', 'how can i learn from mistakes', 'how can i join a team', 'how can i ask for feedback', 'how can i set a goal',
        'what is a prototype', 'what is a beta version', 'what is a bug', 'what is a patch', 'what is a hello world', 'what is a repository', 'what is a startup pitch', 'what is a user persona', 'what is a podcast', 'what is a playlist',
        'why do we study planets', 'why do we explore space', 'why do we learn history', 'why do we study cells', 'why do we care about climate', 'why do we need engineers', 'why do we need artists', 'why do we need doctors', 'why do we need teachers', 'why do we need friends',
        'how do i keep learning', 'how do i stay curious', 'how do i stay creative', 'how do i stay kind', 'how do i stay patient', 'how do i stay calm', 'how do i stay energized', 'how do i stay organized', 'how do i stay healthy', 'how do i stay smart',
        'what is virtual reality', 'what is augmented reality', 'what is a chatbot', 'what is a search engine', 'what is a social network', 'what is a recommendation system', 'what is a sensor network', 'what is an interface', 'what is a dashboard', 'what is a smart home',
        'why do some songs stick', 'why do some designs feel nice', 'why do some tools help more', 'why do some questions matter', 'why do some problems repeat', 'why do some solutions fail', 'why do some ideas spread', 'why do some teams win', 'why do some projects end early', 'why do some experiments work',
    ],
}
responses = {
    'greetings_training.txt': [
        'hey, what’s up', 'hi there', 'hello, nice to see you', 'yo, what’s good', 'sup, how are you', 'good morning, ready for today', 'good afternoon, how’s it going', 'good evening, hope you’re well', 'hey, been a minute', 'hiya, what’s new',
        'hey bro, how’s it', 'hey fam, you good', 'howdy, nice to see you', 'hey, long time no chat', 'yo dude, how’s life', 'hey man, what’s happening', 'hey girl, how ya doin', 'hey buddy, what’s up', 'hello friend, how are you', 'hi love, how’s your day',
        'i’m here now', 'yeah, i’m around', 'i’m good, you', 'still here', 'i’m awake', 'yes, i’m here', 'hey again, what’s up', 'back now, you there', 'gotcha, i’m here', 'hey, i’m listening',
        'bye, catch you later', 'see ya', 'later', 'talk soon', 'peace', 'bye for now', 'take care', 'night, sleep well', 'see you soon', 'catch you later',
        'hola, buenos dias', 'bonjour, comment ça va', 'ciao, come va', 'salut, quoi de neuf', 'konnichiwa, genki desu ka', 'namaste, kaise ho', 'assalamualaikum, kya haal hai', 'shalom, ma shlomcha', 'ola, tudo bem', 'hi, friend',
        'hey, are you there', 'are you there now', 'yes, i’m here', 'i’m here if you want', 'right here', 'yup, still here', 'sure, i’m around', 'i’m online now', 'available now', 'i’m ready',
        'back again, hey', 'i’m back now', 'just got back', 'back online', 'i’m back here', 'i came back', 'back in the chat', 'back and ready', 'i’m back, what’s up', 'back, tell me',
        'hey bro', 'hey fam', 'hey sis', 'hey bro, how you', 'hey fam, how you', 'hey friend', 'hey champ', 'hey boss', 'hey mate', 'hey homie',
        'bye now', 'see you later', 'later gator', 'catch ya later', 'talk later', 'take it easy', 'stay safe', 'bye, take care', 'peace out', 'see you soon',
        'hey, what’s up bro', 'yo fam, wassup', 'hey pal, how’s it', 'hiya mate, how are you', 'hello there, how’s it going', 'hey friend, good to see you', 'hi there, glad you’re here', 'hey you, nice to see ya', 'sup bro, you good', 'yo, all good',
        'hi again', 'hello again', 'hey again', 'back again', 'hiya again', 'hello once more', 'nice to see you again', 'welcome back', 'glad you’re back', 'good to have you back',
        'how far', 'how you dey', 'how your body', 'una dey', 'good morning o', 'good afternoon o', 'good evening o', 'how far na', 'how you dey now', 'i dey here',
        'hey bro, long time', 'hey fam, been a while', 'hey sis, how you doing', 'hey mate, what’s up', 'hey boss, you there', 'hey friend, you good', 'hey dude, you awake', 'hey love, you there', 'hey team, hi', 'hey all, hello',
        'bye bye', 'see ya later', 'peace out fam', 'take care bro', 'take care fam', 'talk soon', 'catch you later', 'bye for now', 'have a good one', 'stay chill',
        'hello, what’s going on', 'hi, how’s it', 'yo, what’s happening', 'hey, happy day', 'hi, ready when you are', 'hello, been waiting', 'hi, glad you wrote', 'hey, nice to chat', 'yo, let’s talk', 'hi, how’s the day',
        'hey, still there', 'are you around', 'still online', 'still up', 'you still there', 'last longer?', 'you there yet', 'hello? yes i am', 'hey, i’m here', 'i am here',
        'good night', 'night now', 'sleep well', 'see you soon', 'bye now', 'take care', 'catch you later', 'later alligator', 'peace out', 'sweet dreams',
        'hey, you good', 'hi, how you feel', 'hello, how you do', 'yo, you okay', 'hey, what’s new', 'hello, what’s up', 'hi, you there', 'yo, I’m here', 'hey, I’m here', 'hi, all good',
        'good morning', 'good afternoon', 'good evening', 'hiya', 'hey there', 'hiya there', 'hello there', 'yo there', 'sup there', 'what’s up there',
        'hey friend', 'hey bestie', 'hey champ', 'hey boss', 'hey chief', 'hey bro', 'hey fam', 'hey sis', 'hey mate', 'hey love',
    ],
    'everyday_conversation_training.txt': [
        'i’m doing okay', 'i’m fine, thanks', 'i’m good, you', 'doing well', 'not bad at all', 'feeling a bit tired', 'feeling pretty good', 'feeling relaxed', 'feeling upbeat', 'feeling calm',
        'i had cereal', 'i had toast', 'i had coffee', 'i had nothing yet', 'i grabbed a snack', 'i made lunch', 'i ordered food', 'i ate out', 'i cooked dinner', 'i had noodles',
        'i slept okay', 'i slept well', 'i woke up early', 'i woke up late', 'i took a nap', 'i didn’t sleep much', 'i slept enough', 'i slept poorly', 'i had a short nap', 'i feel rested',
        'work was fine', 'school was busy', 'day was smooth', 'day was okay', 'day was hectic', 'day was chill', 'day was fun', 'day was stressful', 'day was normal', 'day was slow',
        'my weather is nice', 'it’s raining here', 'it’s sunny now', 'it’s windy today', 'it’s cold here', 'it’s warm today', 'it’s humid here', 'it’s cloudy now', 'it’s drizzling', 'it’s bright out',
        'i am a bit hungry', 'i’m not hungry', 'i’m full', 'i could use a snack', 'i want coffee', 'i need water', 'i want a meal', 'i am craving pizza', 'i want something sweet', 'i want something salty',
        'i’m a little stressed', 'i’m pretty happy', 'i’m kind of tired', 'i’m feeling good', 'i’m feeling okay', 'i’m feeling upbeat', 'i’m feeling anxious', 'i’m feeling relaxed', 'i’m feeling mellow', 'i’m feeling motivated',
        'my boss is nice', 'my class was okay', 'my team was helpful', 'my job is busy', 'school is okay', 'work is fine', 'class was fun', 'meeting went well', 'homework is done', 'study was useful',
        'i learned something new', 'i saw a funny meme', 'i cooked something tasty', 'i walked around', 'i drank tea', 'i drank water', 'i read a bit', 'i watched a show', 'i practiced music', 'i drew a little',
        'i’m chilling now', 'i’m taking a break', 'i’m just relaxing', 'i’m getting stuff done', 'i’m catching up', 'i’m heading out', 'i’m staying in', 'i’m making dinner', 'i’m doing homework', 'i’m resting',
        'my energy is low', 'my energy is good', 'my focus is strong', 'my focus is low', 'my mood is calm', 'my mood is bright', 'my motivation is low', 'my motivation is high', 'i feel steady', 'i feel anxious',
        'i need some rest', 'i need coffee', 'i need a break', 'i need food', 'i need a shower', 'i need a minute', 'i need some quiet', 'i need to move', 'i need sleep', 'i need to relax',
        'i’m making pancakes', 'i’m eating salad', 'i’m having breakfast', 'i’m having lunch', 'i’m having dinner', 'i’m snacking now', 'i’m cooking pasta', 'i’m ordering food', 'i’m boiling water', 'i’m grabbing fruit',
        'i feel calm today', 'i feel busy today', 'i feel sleepy', 'i feel excited', 'i feel hungry', 'i feel content', 'i feel worried', 'i feel happy', 'i feel slow', 'i feel refreshed',
        'the weather is cool', 'the weather is warm', 'the weather is nice', 'the weather is gray', 'the weather is wet', 'the weather is sunny', 'the weather is windy', 'the weather is calm', 'the weather is clear', 'the weather is mild',
        'i’m working on a project', 'i’m studying right now', 'i’m in class', 'i’m at work', 'i’m heading to school', 'i’m on a break', 'i’m in a meeting', 'i’m doing chores', 'i’m finishing tasks', 'i’m writing notes',
        'i feel good about it', 'i feel okay about it', 'i feel unsure', 'i feel ready', 'i feel a bit nervous', 'i feel steady', 'i feel excited about this', 'i feel tired about that', 'i feel calm about today', 'i feel hopeful',
        'i had a good meal', 'i had a simple lunch', 'i had a tasty dinner', 'i had a quick snack', 'i had a big breakfast', 'i had a light dinner', 'i had some fruit', 'i had some soup', 'i had a sandwich', 'i had cereal',
        'i’m just checking in', 'i’m asking how you are', 'i’m curious about you', 'i’m hearing how you feel', 'i’m listening', 'i’m always around', 'i’m glad you asked', 'i’m glad you said hi', 'i’m happy to chat', 'i’m here for you',
        'it was a normal day', 'it was a busy day', 'it was a quiet day', 'it was a fun day', 'it was a rough day', 'it was a good day', 'it was an okay day', 'it was a long day', 'it was a short day', 'it was a fine day',
        'i slept a little', 'i slept deeply', 'i woke up refreshed', 'i woke up tired', 'i woke up late', 'i woke up early', 'i woke up hungry', 'i woke up happy', 'i woke up slow', 'i woke up calm',
    ],
    'knowledge_and_problem_solving_training.txt': [
        'what is ai', 'what is machine learning', 'what is neural network', 'what is deep learning', 'what is cloud computing', 'what is blockchain', 'what is a database', 'what is an algorithm', 'what is a model', 'what is a byte',
        'why is ai useful', 'why is machine learning popular', 'why do we use algorithms', 'why does my code crash', 'why is the sky blue', 'why do plants need water', 'why do we sleep', 'why is music soothing', 'why does rain happen', 'why do we learn math',
        'how do i fix a bug', 'how do i learn python', 'how do i make a website', 'how do i train a model', 'how do i save my work', 'how do i play guitar', 'how do i write a song', 'how do i design a logo', 'how do i cook pasta', 'how do i clean my desk',
        'what is generative ai', 'what is natural language processing', 'what is reinforcement learning', 'what is data science', 'what is user experience', 'what is a startup', 'what is product design', 'what is computer vision', 'what is quantum computing', 'what is music theory',
        'why should i learn coding', 'why is data important', 'why is design important', 'why is science helpful', 'why is documentation useful', 'why is sharing knowledge good', 'why is collaboration useful', 'why is practice needed', 'why is curiosity good', 'why is sleep important',
        'how can i build an app', 'how can i improve my writing', 'how can i organize my notes', 'how can i stay motivated', 'how can i learn faster', 'how can i solve this problem', 'how can i debug this', 'how can i make it better', 'how can i find answers', 'how can i get help',
        'what is the difference between ai and ml', 'what is the difference between ui and ux', 'what is the difference between data and information', 'what is the difference between frontend and backend', 'what is the difference between app and website', 'what is the difference between code and script', 'what is the difference between design and art', 'what is the difference between science and engineering', 'what is the difference between tech and tools', 'what is the difference between hardware and software',
        'why do we use keyboards', 'why do we use screens', 'why do we use headphones', 'why do we use apps', 'why do we use social media', 'why do we use search engines', 'why do we use emails', 'why do we use passwords', 'why do we use usernames', 'why do we use updates',
        'how does a phone work', 'how does the internet work', 'how does wifi work', 'how does bluetooth work', 'how does a battery work', 'how does a camera work', 'how does streaming work', 'how does a microphone work', 'how does a speaker work', 'how does a printer work',
        'what is a server', 'what is a browser', 'what is a framework', 'what is a library', 'what is a protocol', 'what is an api', 'what is a sensor', 'what is a chip', 'what is a circuit', 'what is a plugin',
        'why does sound travel', 'why does light bend', 'why does metal rust', 'why does ice melt', 'why does gravity pull', 'why does heat move', 'why does time feel fast', 'why does music make you feel', 'why does art matter', 'why does math help',
        'how do i choose a color', 'how do i balance a layout', 'how do i pick a font', 'how do i name my project', 'how do i set up a workspace', 'how do i charge my device', 'how do i protect my privacy', 'how do i save a file', 'how do i share a link', 'how do i join a call',
        'what is a chord', 'what is a beat', 'what is a melody', 'what is a rhythm', 'what is harmony', 'what is tempo', 'what is a mix', 'what is a genre', 'what is a producer', 'what is a songwriter',
        'why is practice key', 'why is feedback useful', 'why is version control helpful', 'why is backup important', 'why is testing needed', 'why is patience important', 'why is an idea powerful', 'why is empathy important', 'why is learning continuous', 'why is asking questions good',
        'how can i study effectively', 'how can i manage time', 'how can i avoid distraction', 'how can i stay focused', 'how can i prepare for tests', 'how can i learn by doing', 'how can i learn from mistakes', 'how can i join a team', 'how can i ask for feedback', 'how can i set a goal',
        'what is a prototype', 'what is a beta version', 'what is a bug', 'what is a patch', 'what is a hello world', 'what is a repository', 'what is a startup pitch', 'what is a user persona', 'what is a podcast', 'what is a playlist',
        'why do we study planets', 'why do we explore space', 'why do we learn history', 'why do we study cells', 'why do we care about climate', 'why do we need engineers', 'why do we need artists', 'why do we need doctors', 'why do we need teachers', 'why do we need friends',
        'how do i keep learning', 'how do i stay curious', 'how do i stay creative', 'how do i stay kind', 'how do i stay patient', 'how do i stay calm', 'how do i stay energized', 'how do i stay organized', 'how do i stay healthy', 'how do i stay smart',
        'what is virtual reality', 'what is augmented reality', 'what is a chatbot', 'what is a search engine', 'what is a social network', 'what is a recommendation system', 'what is a sensor network', 'what is an interface', 'what is a dashboard', 'what is a smart home',
        'why do some songs stick', 'why do some designs feel nice', 'why do some tools help more', 'why do some questions matter', 'why do some problems repeat', 'why do some solutions fail', 'why do some ideas spread', 'why do some teams win', 'why do some projects end early', 'why do some experiments work',
    ],
}
responses = {
    'knowledge_and_problem_solving_training.txt': [
        'ai is smart tech', 'machine learning is teaching computers', 'a neural network is a math model', 'deep learning is layered learning', 'cloud computing is using remote servers', 'blockchain is linked records', 'a database stores data', 'an algorithm is a set of steps', 'a model predicts outcomes', 'a byte stores information',
        'ai is useful for automation', 'machine learning is popular for trends', 'algorithms help solve problems', 'code crashes when something breaks', 'the sky is blue from light', 'plants need water to grow', 'we sleep to restore energy', 'music calms people', 'rain forms from clouds', 'math helps solve issues',
        'fix a bug by checking code', 'learn python by practicing', 'make a website with html', 'train a model with examples', 'save your work often', 'play guitar by practicing chords', 'write a song with a melody', 'design a logo with simple shapes', 'cook pasta by boiling water', 'clean your desk bit by bit',
        'generative ai creates content', 'nlp helps computers read language', 'reinforcement learning uses rewards', 'data science finds patterns', 'ux design makes products easy', 'a startup launches a new idea', 'product design shapes user experience', 'computer vision reads images', 'quantum computing uses quantum bits', 'music theory explains notes',
        'learn coding to build stuff', 'data is important for decisions', 'design is important for clarity', 'science helps explain things', 'documentation keeps info clear', 'sharing knowledge helps others', 'collaboration makes work easier', 'practice improves skill', 'curiosity leads to learning', 'sleep keeps your brain healthy',
        'build an app by planning it', 'improve writing by editing', 'organize notes with folders', 'stay motivated with small goals', 'learn faster by doing more', 'solve problems step by step', 'debug by testing one thing', 'make it better by refining', 'find answers by searching', 'get help from someone',
        'ai is not the same as ml', 'ui is how it looks, ux is how it feels', 'data is raw, information is useful', 'frontend is what users see, backend is what runs it', 'an app can be a website too', 'code and script are both instructions', 'design and art can overlap', 'science and engineering solve different questions', 'tech is tools, tools make tasks easier', 'hardware is physical, software is digital',
        'keyboards help type words', 'screens show info', 'headphones play sound', 'apps make tasks easier', 'social media shares messages', 'search engines find sites', 'emails send messages', 'passwords keep accounts safe', 'usernames identify people', 'updates add fixes',
        'a phone uses circuits and software', 'the internet links devices', 'wifi sends data wirelessly', 'bluetooth connects devices nearby', 'a battery stores power', 'a camera captures images', 'streaming sends media live', 'a microphone catches sound', 'a speaker plays audio', 'a printer copies documents',
        'a server hosts services', 'a browser displays websites', 'a framework helps build apps', 'a library shares reusable code', 'a protocol is a communication rule', 'an api connects software', 'a sensor detects changes', 'a chip runs operations', 'a circuit moves electricity', 'a plugin adds features',
        'sound travels as waves', 'light bends in glass', 'metal rusts with air and water', 'ice melts with heat', 'gravity pulls objects', 'heat moves from hot to cold', 'time feels fast when busy', 'music touches feelings', 'art expresses ideas', 'math makes patterns clear',
        'choose colors that work together', 'balance a layout with space', 'pick fonts that are readable', 'name a project clearly', 'set up a workspace cleanly', 'charge a device before use', 'protect privacy with passwords', 'save files often', 'share links carefully', 'join calls with a link',
        'a chord is notes played together', 'a beat is the pulse of a song', 'a melody is a tune', 'rhythm is timing', 'harmony is layers of sound', 'tempo is speed', 'a mix blends tracks', 'a genre is a style', 'a producer guides songs', 'a songwriter writes lyrics',
        'practice makes progress', 'feedback helps improve', 'version control saves history', 'backup protects work', 'testing catches errors', 'patience helps learning', 'ideas grow over time', 'empathy helps users', 'learning never stops', 'questions lead to answers',
        'study effectively with short sessions', 'manage time with a planner', 'avoid distraction by focusing', 'stay focused with breaks', 'prepare for tests with review', 'learn by doing projects', 'learn from mistakes', 'join a team to collaborate', 'ask for feedback kindly', 'set a goal and follow it',
        'a prototype is an early version', 'a beta version is a test release', 'a bug is an error', 'a patch is a fix', 'hello world is a first program', 'a repository stores code', 'a pitch shares an idea', 'a persona represents a user', 'a podcast is recorded talk', 'a playlist is a music list',
        'planets are studied to learn space', 'space is explored for discovery', 'history is learned from the past', 'cells are studied for life', 'climate matters for earth', 'engineers build useful things', 'artists create meaning', 'doctors keep people healthy', 'teachers help people learn', 'friends help each other',
        'keep learning by staying curious', 'stay curious by asking why', 'stay creative with practice', 'stay kind by helping others', 'stay patient with progress', 'stay calm with deep breaths', 'stay energized with rest', 'stay organized with lists', 'stay healthy with meals', 'stay smart by reading',
        'virtual reality feels like being inside', 'augmented reality adds digital items', 'a chatbot chats instantly', 'a search engine finds results', 'a social network connects people', 'a recommendation system suggests things', 'a sensor network collects data', 'an interface lets you interact', 'a dashboard shows status', 'a smart home controls devices',
        'songs stick because they are catchy', 'designs feel nice when simple', 'tools help more when easy', 'questions matter when clear', 'problems repeat when not fixed', 'solutions fail when rushed', 'ideas spread when shared', 'teams win when they work together', 'projects end early when planned', 'experiments work when measured',
    ],
}
for filename, inputs in files.items():
    response_pool = responses[filename] if filename in responses else responses['knowledge_and_problem_solving_training.txt']
    if len(inputs) < 200:
        raise ValueError(f'Not enough inputs for {filename}')
    if len(response_pool) < 200:
        extra = []
        while len(extra) + len(response_pool) < 200:
            extra.extend([resp + (' now' if i % 2 == 0 else '') for i, resp in enumerate(response_pool)])
        response_pool = (response_pool + extra)[:200]
    pairs = [f"### INPUT:\n{inputs[i]}\n### OUTPUT:\n{response_pool[i]}" for i in range(200)]
    path = root / filename
    path.write_text('\n\n'.join(pairs) + '\n', encoding='utf-8')
    print(f'Wrote {path} ({len(pairs)} pairs)')
